"""case_wallet evidence metadata

Revision ID: 3b77a840c2bd
Revises: fb5492d3690e
Create Date: 2025-12-17 03:02:32.257710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b77a840c2bd'
down_revision: Union[str, Sequence[str], None] = 'fb5492d3690e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_wallets', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('case_wallets', sa.Column('note', sa.String(), nullable=True))
    op.add_column('case_wallets', sa.Column('source', sa.String(), nullable=True))
    op.add_column('case_wallets', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_wallets', 'created_at')
    op.drop_column('case_wallets', 'source')
    op.drop_column('case_wallets', 'note')
    op.drop_column('case_wallets', 'confidence')
    # ### end Alembic commands ###
