"""add case_wallets table

Revision ID: fb5492d3690e
Revises: 84d4541a91e4
Create Date: 2025-12-14 15:31:37.692644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5492d3690e'
down_revision: Union[str, Sequence[str], None] = '84d4541a91e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_wallets',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'wallet_id')
    )
    op.alter_column('wallets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('case_wallets')
    # ### end Alembic commands ###
